@InventoryManagement.Api_HostAddress = http://localhost:5200

GET {{InventoryManagement.Api_HostAddress}}/products
Accept: application/json

###

POST {{InventoryManagement.Api_HostAddress}}/products
Content-Type: application/json

{
  "name": "Keyboard",
  "description": "Mechanical keyboard",
  "price": 199.99,
  "stock": 12
}

###

POST {{InventoryManagement.Api_HostAddress}}/orders
Content-Type: application/json

{
  "customerId": "22222222-2222-2222-2222-222222222222",
  "products": [
    {
      "productId": "00000000-0000-0000-0000-000000000000",
      "quantity": 1
    }
  ]
}

###
